apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: zp1lh0tdm-go
  janus-idp.io/tekton: zp1lh0tdm-go
  backstage.io/kubernetes-id: zp1lh0tdm-go
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: zp1lh0tdm-go
resources:
- deployment.yaml
- route.yaml
- service.yaml
